version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-oggyetles}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hingage-pgadmin.rule=Host(`hingage-pgadmin.muchosalexis.fr`)"
      - "traefik.http.routers.hingage-pgadmin.entrypoints=websecure"
      - "traefik.http.routers.hingage-pgadmin.tls.certresolver=cloudflare"
      - "traefik.http.services.hingage-pgadmin.loadbalancer.server.port=80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres

  backend-service:
    build:
      context: ../Backend-Service
    container_name: backend_service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: oggyetles
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hingage-backend.rule=Host(`hingage-backend.muchosalexis.fr`)"
      - "traefik.http.routers.hingage-backend.entrypoints=websecure"
      - "traefik.http.routers.hingage-backend.tls.certresolver=cloudflare"
      - "traefik.http.services.hingage-backend.loadbalancer.server.port=8080"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    external: true

volumes:
  postgres:
  pgadmin:
